### ISSUE TITLE
Starta ett tomt Svelte projekt som kommer användas som bas för framtida utvecklingar.

### ISSUE THREAD

**Issue by KhosroJadidiDeveloper** [af-joint-project/joint-project#13]
Se till att Typescript är med.

**Comment by Aknotofknots** [comment]
här är länken till svelte komponent biblioteket som du ska installera: https://sveltematerialui.com/INSTALL.md

**Comment by Ch84** [comment]
PR https://github.com/af-joint-project/joint-project/pull/14
