### ISSUE TITLE
Design Process - Rita en UI.

### ISSUE THREAD

**Issue by KhosroJadidiDeveloper** [af-joint-project/joint-project#8]

**Comment by Aknotofknots** [comment]
![IMG_20230118_151447](https://user-images.githubusercontent.com/22115827/213194562-ea44710f-7f78-42b3-8ebc-47c55ba987fc.jpg)

**Comment by KhosroJadidiDeveloper** [comment]
Ser bra ut, men kanske lite förklarande vid sidan vore bra. Exempelvis, undrar jag vad {50,70} innebär? jag gissar en objekt som innehåller koordinater?

**Comment by KhosroJadidiDeveloper** [comment]
Vi kan börja med en fast "från" punkt (hissen på våning 4) och en drop down med filter:
https://sveltematerialui.com/demo/autocomplete/

denna drop down innehåller en lista aav samtliga rum som finns på plan 4, och användaren kan välja vilket rum  hen vill gå till.
